export default [
  {
    id: 'XJHM6VU',
    locator: 'RES053152-1053',
    status: 'CANCELLED',
    primaryGuest: 'CAMILA LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 177.76,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHM5GY',
    locator: 'RES053144-1053',
    status: 'CANCELLED',
    primaryGuest: 'ELIZA LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHM4XE',
    locator: 'RES053143-1053',
    status: 'CANCELLED',
    primaryGuest: 'YIYI LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHM4HQ',
    locator: 'RES053142-1053',
    status: 'CANCELLED',
    primaryGuest: 'WILLIAM LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHM2JA',
    locator: 'RES053137-1053',
    status: 'CANCELLED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 307.28,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMY2E',
    locator: 'RES053136-1053',
    status: 'CANCELLED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 307.28,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMYKQ',
    locator: 'RES053135-1053',
    status: 'CANCELLED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 262.5,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMX24',
    locator: 'RES053134-1053',
    status: 'CANCELLED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 307.28,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMW3U',
    locator: 'RES053133-1053',
    status: 'CANCELLED',
    primaryGuest: 'Jhon Zeta',
    channel: 'Netactica',
    paymentWay: 'MASTERCARD',
    total: 86.72,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMWMA',
    locator: 'RES053132-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'MASTERCARD',
    total: 614.56,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMVMY',
    locator: 'RES053125-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Test Test',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 108.2,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMT54',
    locator: 'RES053124-1053',
    status: 'CANCELLED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'SAP Concur',
    paymentWay: 'MASTERCARD',
    total: 598.5,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMS6U',
    locator: 'RES053123-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Ob Adult  ',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 393.39,
    paymentStatus: 'ERROR',
  },
  {
    id: 'XJHMSPA',
    locator: 'RES053122-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Test Test',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 108.2,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMR7M',
    locator: 'RES053121-1053',
    status: 'CONFIRMED',
    primaryGuest: 'vpc i',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 751.9,
    paymentStatus: 'CONFIRMED',
  },
  {
    id: 'XJHMRPY',
    locator: 'RES053120-1053',
    status: 'CONFIRMED',
    primaryGuest: 'ALLAN MURILLO ',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 390,
    paymentStatus: 'CONFIRMED',
  },
  {
    id: 'XJHMRAE',
    locator: 'RES053119-1053',
    status: 'CONFIRMED',
    primaryGuest: 'ALLAN MURILO ',
    channel: 'Naturleon',
    paymentWay: 'MASTERCARD',
    total: 400,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMQQQ',
    locator: 'RES053118-1053',
    status: 'CONFIRMED',
    primaryGuest: 'ALLAN MURILO ',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 400,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMQA4',
    locator: 'RES053117-1053',
    status: 'CONFIRMED',
    primaryGuest: 'ALLAN MURILO ',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 400,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMPRI',
    locator: 'RES053116-1053',
    status: 'CONFIRMED',
    primaryGuest: 'ALLAN MURILLO ',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 400,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMPBU',
    locator: 'RES053115-1053',
    status: 'CANCELLED',
    primaryGuest: 'Jorge  Ocejo',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 307.28,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMOSA',
    locator: 'RES053114-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'Visitnow',
    paymentWay: 'VISA',
    total: 156,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMOCM',
    locator: 'RES053113-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 614.56,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMNSY',
    locator: 'RES053112-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 307.28,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMNDE',
    locator: 'RES053111-1053',
    status: 'CONFIRMED',
    primaryGuest: 'ALLAN MURILLO ',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 585,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMMTS',
    locator: 'RES053110-1053',
    status: 'CANCELLED',
    primaryGuest: 'JESUS LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMLEU',
    locator: 'RES053109-1053',
    status: 'CANCELLED',
    primaryGuest: 'BILLY LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMKVA',
    locator: 'RES053108-1053',
    status: 'CANCELLED',
    primaryGuest: 'ZÉLIA GUIMARÃES',
    channel: 'Infotera',
    paymentWay: 'MASTERCARD',
    total: 660,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMKFM',
    locator: 'RES053107-1053',
    status: 'CANCELLED',
    primaryGuest: 'ZULAIA MARTINEZ',
    channel: 'Infotera',
    paymentWay: 'MASTERCARD',
    total: 250,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMJVZ',
    locator: 'RES053106-1053',
    status: 'CANCELLED',
    primaryGuest: 'ANGELA LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 99.99,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMJVY',
    locator: 'RES053105-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'MASTERCARD',
    total: 525,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMJGE',
    locator: 'RES053104-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'MASTERCARD',
    total: 105,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMIWQ',
    locator: 'RES053103-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 508.9,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMIG4',
    locator: 'RES053102-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 156,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMFYY',
    locator: 'RES053098-1053',
    status: 'CANCELLED',
    primaryGuest: 'JAVIER LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMFJE',
    locator: 'RES053097-1053',
    status: 'CANCELLED',
    primaryGuest: 'FRANCO LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHMAM4',
    locator: 'RES053094-1053',
    status: 'CANCELLED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'SAP Concur',
    paymentWay: 'MASTERCARD',
    total: 1396.5,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHL47Q',
    locator: 'RES053093-1053',
    status: 'CONFIRMED',
    primaryGuest: 'dns i',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 751.9,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHL4P4',
    locator: 'RES053092-1053',
    status: 'CONFIRMED',
    primaryGuest: 'ALLAN MURILLO ',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 865.08,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHL2BY',
    locator: 'RES053089-1053',
    status: 'CANCELLED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'SAP Concur',
    paymentWay: 'VISA',
    total: 199.5,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLZSF',
    locator: 'RES053088-1053',
    status: 'CANCELLED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'SAP Concur',
    paymentWay: 'VISA',
    total: 199.5,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLYDJ',
    locator: 'RES053087-1053',
    status: 'CANCELLED',
    primaryGuest: 'FELIPE LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLYDI',
    locator: 'RES053086-1053',
    status: 'CANCELLED',
    primaryGuest: 'KARLA LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLXTV',
    locator: 'RES053085-1053',
    status: 'CANCELLED',
    primaryGuest: 'CLAUDIA LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLXTU',
    locator: 'RES053084-1053',
    status: 'CANCELLED',
    primaryGuest: 'WILLIAM LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLVVE',
    locator: 'RES053083-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 2728.08,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLTWV',
    locator: 'RES053082-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teste Pedro',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 52.81,
    paymentStatus: 'REJECTED',
  },
  {
    id: 'XJHLSXM',
    locator: 'RES053077-1053',
    status: 'CANCELLED',
    primaryGuest: 'FANNY LOPEZ',
    channel: 'IdeasFractal',
    paymentWay: 'MASTERCARD',
    total: 88.88,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLSHY',
    locator: 'RES053076-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 2728.08,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLRIQ',
    locator: 'RES053075-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 156,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLQY4',
    locator: 'RES053074-1053',
    status: 'MODIFIED',
    primaryGuest: 'persona   apellido ',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 307.28,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLOKY',
    locator: 'RES053073-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teste VCN',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 260.18,
    paymentStatus: 'REJECTED',
  },
  {
    id: 'XJHLNLU',
    locator: 'RES053072-1053',
    status: 'CANCELLED',
    primaryGuest: 'jorge  ocejo',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 307.28,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLM34',
    locator: 'RES053071-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 1328.96,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLMMK',
    locator: 'RES053070-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 1343.87,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLMMJ',
    locator: 'RES053069-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teste VCN',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 668.2,
    paymentStatus: 'CONFIRMED',
  },
  {
    id: 'XJHLL4U',
    locator: 'RES053068-1053',
    status: 'CONFIRMED',
    primaryGuest: 'ALLAN MURILLO ',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 292.5,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLLNA',
    locator: 'RES053067-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 2728.08,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLKNZ',
    locator: 'RES053066-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teste VCN',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 819.4,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLJOQ',
    locator: 'RES053065-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teste VCN',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 668.2,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLHQA',
    locator: 'RES053064-1053',
    status: 'CONFIRMED',
    primaryGuest: 'STEVE RAJ',
    channel: 'DCS Plus',
    paymentWay: 'MASTERCARD',
    total: 100,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLHAM',
    locator: 'RES053063-1053',
    status: 'CONFIRMED',
    primaryGuest: 'RAJA TESTER',
    channel: 'DCS Plus',
    paymentWay: 'MASTERCARD',
    total: 83.52,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLGQY',
    locator: 'RES053062-1053',
    status: 'CONFIRMED',
    primaryGuest: 'RAJAT STEVE',
    channel: 'DCS Plus',
    paymentWay: 'MASTERCARD',
    total: 156,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLGBE',
    locator: 'RES053061-1053',
    status: 'CANCELLED',
    primaryGuest: 'Eduardo Barrera ',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 810,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLFRQ',
    locator: 'RES053060-1053',
    status: 'CANCELLED',
    primaryGuest: 'Eduardo Barrera ',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 961.9,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLFB4',
    locator: 'RES053059-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Eduardo Barrera ',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 590.08,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLESI',
    locator: 'RES053058-1053',
    status: 'CANCELLED',
    primaryGuest: 'Eduardo Barrera ',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 485.3,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLECU',
    locator: 'RES053057-1053',
    status: 'CANCELLED',
    primaryGuest: 'Eduardo Barrera ',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 440,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLDTA',
    locator: 'RES053056-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Eduardo Barrera ',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 353.7,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLDDM',
    locator: 'RES053055-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Eduardo Barrera ',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 393.39,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLCTY',
    locator: 'RES053054-1053',
    status: 'MODIFIED',
    primaryGuest: 'HECTOR None',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 1703.68,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLCEE',
    locator: 'RES053053-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 78,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLBUQ',
    locator: 'RES053052-1053',
    status: 'CONFIRMED',
    primaryGuest: 'MANUEL MURILLO ',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 2093.32,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLBE4',
    locator: 'RES053051-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teo Carrascal',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 393.39,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLAVI',
    locator: 'RES053050-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Daniel Alvarez',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 393.39,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHLAFU',
    locator: 'RES053049-1053',
    status: 'CONFIRMED',
    primaryGuest: 'dnslogs i',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 751.9,
    paymentStatus: 'CONFIRMED',
  },
  {
    id: 'XJHK7WA',
    locator: 'RES053048-1053',
    status: 'CONFIRMED',
    primaryGuest: 'jorge ocejo',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 409.7,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHK7GM',
    locator: 'RES053047-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 280,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHK5H4',
    locator: 'RES053046-1053',
    status: 'CANCELLED',
    primaryGuest: 'LOLITA None',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 1058.82,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHK3ZA',
    locator: 'RES053045-1053',
    status: 'CANCELLED',
    primaryGuest: 'Juan Castaño',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 790,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHK2ZY',
    locator: 'RES053044-1053',
    status: 'CANCELLED',
    primaryGuest: 'ALLAN MURILO None',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 299.97,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHK2KE',
    locator: 'RES053043-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'Naturleon',
    paymentWay: 'VISA',
    total: 78,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKZ2Q',
    locator: 'RES053042-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teo Carrascal',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 485.3,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKX4B',
    locator: 'RES053039-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 196.69,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKX4A',
    locator: 'RES053038-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 196.69,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKXMM',
    locator: 'RES053037-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 210,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKW4Z',
    locator: 'RES053036-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 210,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKW4Y',
    locator: 'RES053035-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 210,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKWNF',
    locator: 'RES053034-1053',
    status: 'CONFIRMED',
    primaryGuest: 'JOHN DOE',
    channel: 'DCS Plus',
    paymentWay: 'MASTERCARD',
    total: 375,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKWNE',
    locator: 'RES053033-1053',
    status: 'CONFIRMED',
    primaryGuest: 'JOHN DOE',
    channel: 'DCS Plus',
    paymentWay: 'MASTERCARD',
    total: 324,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKVN4',
    locator: 'RES053032-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 158.44,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKT7A',
    locator: 'RES053024-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 262.5,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKTPM',
    locator: 'RES053023-1053',
    status: 'MODIFIED',
    primaryGuest: 'Jorge Vadillo Arias None',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 270,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKS7Y',
    locator: 'RES053022-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teo Carrascal',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 199.98,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKRQ4',
    locator: 'RES053013-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teo Carrascal',
    channel: 'Viajes Dorado',
    paymentWay: 'MASTERCARD',
    total: 156,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKQRU',
    locator: 'RES053012-1053',
    status: 'CONFIRMED',
    primaryGuest: 'Teste Teste',
    channel: 'Niara',
    paymentWay: 'MASTERCARD',
    total: 54,
    paymentStatus: 'CANCELLED',
  },
  {
    id: 'XJHKMUU',
    locator: 'RES052999-1053',
    status: 'CANCELLED',
    primaryGuest: 'SÉRGIO GUIMARÃES',
    channel: 'Infotera',
    paymentWay: 'MASTERCARD',
    total: 125,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKLVN',
    locator: 'RES052998-1053',
    status: 'MODIFIED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 2728.08,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKLVM',
    locator: 'RES052997-1053',
    status: 'CONFIRMED',
    primaryGuest: 'OmnibeesAdult Omn Mebee',
    channel: 'PULL_TEST',
    paymentWay: 'VISA',
    total: 1364.04,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKLFY',
    locator: 'RES052996-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 2728.08,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKLFY',
    locator: 'RES052996-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 2728.08,
    paymentStatus: 'N/A',
  },
  {
    id: 'XJHKLFY',
    locator: 'RES052996-1053',
    status: 'CONFIRMED',
    primaryGuest: 'persona apellido',
    channel: 'RutaMaya',
    paymentWay: 'MASTERCARD',
    total: 2728.08,
    paymentStatus: 'N/A',
  },
];
